### ISSUE TITLE
Can't run adricon

### ISSUE THREAD

**Issue by Raidzer1** [jlHertel/adriconf#44] opened 2018-10-19 16:44 UTC
I'm runing arch gnome with wayland on intel gpu.
This is the error message:
`Current language code is pl
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Przerwane (zrzut pamięci)
`

**Comment by velurimithun** [comment] 2018-10-19 16:50
Currently, adriconf supports only X11. We are working on the support for the Wayland system.

Check #36 for updates

**Comment by jlHertel** [comment] 2018-10-21 08:39
Duplicate of #36

**Closed by jlHertel** 2018-10-21 08:39 UTC
Labels: duplicate
