### ISSUE TITLE
radeon_dri.so expected when it should really look for radeonsi_dri.so

### ISSUE THREAD

**Issue by Polynomial-C** [jlHertel/adriconf#54] opened 2019-04-25 16:44 UTC
This one is similar to issue #8 but I also receive a segmentation fault:
```
> NO_AT_BRIDGE=1 LANG=C adriconf                 

(adriconf:30902): Gtk-WARNING **: 18:38:14.705: Failed to parse /home/lars/.config/gtk-3.0/settings.ini: Key file does not have group ?Settings?
adriconf running on X11
Current language code is c
Found config under: /usr/share/drirc.d/00-mesa-defaults.conf
libGL error: MESA-LOADER: failed to open radeon (search paths /usr/lib64/dri)
zsh: segmentation fault  NO_AT_BRIDGE=1 LANG=C adriconf
>
```
When I set the following symlink, error messages and segfault are gone and adriconf starts up successfully:
```
# ln -sv radeonsi_dri.so /usr/lib64/dri/radeon_dri.so
'/usr/lib64/dri/radeon_dri.so' -> 'radeonsi_dri.so'
#
```
Perhaps I should mention, that even X says it's using `radeonsi` as DRI driver:
```
# grep -F radeon /var/log/Xorg.0.log
[    28.309] (II) LoadModule: "radeon"
[    28.310] (II) Loading /usr/lib64/xorg/modules/drivers/radeon_drv.so
[    28.315] (II) Module radeon: vendor="X.Org Foundation"
[    28.892] (II) RADEON(0): [DRI2]   DRI driver: radeonsi
[    28.892] (II) RADEON(0): [DRI2]   VDPAU driver: radeonsi
[    28.965] (II) AIGLX: Loaded and initialized radeonsi
´´´

**Comment by jlHertel** [comment] 2019-04-26 14:57
Thanks for the bug-report.
I need to rewrite the while logic that is pulling data from libDRM, as it's a bit messy.
I think the issue is that we are reading the kernel driver name instead of the user-space driver name.
I will check further this weekend to see what can be done.

Also, out of curiosity, what is your grapics cards?

**Comment by Polynomial-C** [comment] 2019-04-26 18:14
I am testing this software on two of my Systems. 
One is a Notebook having an `AMD Radeon M6100 (Bonaire)` GPU driven by `radeon` kernel- and `xf86-video-radeon` userspace driver.
The other system has an `AMD Radeon R9 285 (Tonga)` GPU driven by `amdgpu` kernel- and `xf86-video-amdgpu` userspace driver.

The "fun" part is, although the DRI driver on my amdgpu machine is also `radeonsi`, adriconf finds the correct driver combination and doesn't segfault.

**Comment by jlHertel** [comment] 2019-04-28 18:27
@Polynomial-C Can you please try again with latest git code?
I made a temporary fix while I investigate how to properly handle those issues.

**Comment by Polynomial-C** [comment] 2019-04-28 19:44
Latest git works on both systems. Thank you.

**Comment by jlHertel** [comment] 2019-09-10 07:13
This is a duplicate of #61 
I will close this one and track everything in a single issue.

**Closed by jlHertel** 2019-09-10 07:13 UTC
Labels: bug
